set -g default-terminal "screen-256color"
set -g mouse on

set -g history-limit 102400

set -g base-index 1
setw -g pane-base-index 1

set -g renumber-windows on

unbind C-b
set -g prefix C-a

# twice C-a send it to programs
bind C-a send-prefix

bind r source-file ~/.tmux.conf \; display "Config reloaded!"

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# My Own Plugins
# Dracula
set -g @plugin 'dracula/tmux'
set -g @dracula-plugins "battery time"
set -g @dracula-show-powerline true
set -g @dracula-time-format "%m月%e日 %H:%M"
set -g @dracula-show-fahrenheit false
set -g @dracula-fixed-location "Shanghai"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
