#!/bin/sh

swww-daemon &

mako &

fcitx5 &

sh ~/.config/river/display.sh

Mod=Mod1

# This is the example configuration file for river.
#
# If you wish to edit this, you will probably want to copy it to
# $XDG_CONFIG_HOME/river/init or $HOME/.config/river/init first.
#
# See the river(1), riverctl(1), and rivertile(1) man pages for complete
# documentation.

# Note: the "Mod" modifier is also known as Logo, GUI, Windows, Mod4, etc.

# Mod+Shift+Return to start an instance of foot (https://codeberg.org/dnkl/foot)
riverctl map normal $Mod T spawn kitty
riverctl map normal $Mod Space spawn fuzzel

# Mod+Q to close the focused view
riverctl map normal $Mod Q close

# Mod+Shift+E to exit river
riverctl map normal $Mod+Shift E exit

# Mod+J and Super+K to focus the next/previous view in the layout stack
riverctl map normal $Mod J focus-view next
riverctl map normal $Mod K focus-view previous

# Mod+Shift+J and Mod+Shift+K to swap the focused view with the next/previous
# view in the layout stack
riverctl map normal $Mod+Shift J swap next
riverctl map normal $Mod+Shift K swap previous

# Mod+Period and Super+Comma to focus the next/previous output
riverctl map normal $Mod Period focus-output next
riverctl map normal $Mod Comma focus-output previous

# Mod+Shift+{Period,Comma} to send the focused view to the next/previous output
riverctl map normal $Mod+Shift Period send-to-output next
riverctl map normal $Mod+Shift Comma send-to-output previous

# Mod+Return to bump the focused view to the top of the layout stack
riverctl map normal $Mod Return zoom

# Mod+H and Super+L to decrease/increase the main ratio of rivertile(1)
riverctl map normal $Mod H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal $Mod L send-layout-cmd rivertile "main-ratio +0.05"

# Mod+Shift+H and Super+Shift+L to increment/decrement the main count of rivertile(1)
riverctl map normal $Mod+Shift H send-layout-cmd rivertile "main-count +1"
riverctl map normal $Mod+Shift L send-layout-cmd rivertile "main-count -1"

# # Mod+Alt+{H,J,K,L} to move views
# riverctl map normal $Mod+Alt H move left 100
# riverctl map normal $Mod+Alt J move down 100
# riverctl map normal $Mod+Alt K move up 100
# riverctl map normal $Mod+Alt L move right 100
#
# # Mod+Alt+Control+{H,J,K,L} to snap views to screen edges
# riverctl map normal $Mod+Alt+Control H snap left
# riverctl map normal $Mod+Alt+Control J snap down
# riverctl map normal $Mod+Alt+Control K snap up
# riverctl map normal $Mod+Alt+Control L snap right
#
# # Mod+Alt+Shift+{H,J,K,L} to resize views
# riverctl map normal $Mod+Alt+Shift H resize horizontal -100
# riverctl map normal $Mod+Alt+Shift J resize vertical 100
# riverctl map normal $Mod+Alt+Shift K resize vertical -100
# riverctl map normal $Mod+Alt+Shift L resize horizontal 100

# Mod + Left Mouse Button to move views
riverctl map-pointer normal $Mod BTN_LEFT move-view

# Mod + Right Mouse Button to resize views
riverctl map-pointer normal $Mod BTN_RIGHT resize-view

# Mod + Middle Mouse Button to toggle float
riverctl map-pointer normal $Mod BTN_MIDDLE toggle-float

for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))

    # Mod+[1-9] to focus tag [0-8]
    riverctl map normal $Mod $i set-focused-tags $tags

    # Mod+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map normal $Mod+Shift $i set-view-tags $tags

    # Mod+Control+[1-9] to toggle focus of tag [0-8]
    riverctl map normal $Mod+Control $i toggle-focused-tags $tags

    # Mod+Shift+Control+[1-9] to toggle tag [0-8] of focused view
    riverctl map normal $Mod+Shift+Control $i toggle-view-tags $tags
done

# Mod+0 to focus all tags
# Mod+Shift+0 to tag focused view with all tags
all_tags=$(((1 << 32) - 1))
riverctl map normal $Mod 0 set-focused-tags $all_tags
riverctl map normal $Mod+Shift 0 set-view-tags $all_tags

# Mod+Space to toggle float
riverctl map normal $Mod V toggle-float

# Mod+F to toggle fullscreen
riverctl map normal $Mod F toggle-fullscreen

# Mod+{Up,Right,Down,Left} to change layout orientation
riverctl map normal $Mod Up    send-layout-cmd rivertile "main-location top"
riverctl map normal $Mod Right send-layout-cmd rivertile "main-location right"
riverctl map normal $Mod Down  send-layout-cmd rivertile "main-location bottom"
riverctl map normal $Mod Left  send-layout-cmd rivertile "main-location left"

# Declare a passthrough mode. This mode has only a single mapping to return to
# normal mode. This makes it useful for testing a nested wayland compositor
riverctl declare-mode passthrough

# Mod+F11 to enter passthrough mode
riverctl map normal $Mod F11 enter-mode passthrough

# Mod+F11 to return to normal mode
riverctl map passthrough $Mod F11 enter-mode normal

# Various media key mapping examples for both normal and locked mode which do
# not have a modifier
for mode in normal locked
do
    # Eject the optical drive (well if you still have one that is)
    riverctl map $mode None XF86Eject spawn 'eject -T'

    # Control pulse audio volume with pamixer (https://github.com/cdemoulins/pamixer)
    riverctl map $mode None XF86AudioRaiseVolume  spawn 'pamixer -i 5'
    riverctl map $mode None XF86AudioLowerVolume  spawn 'pamixer -d 5'
    riverctl map $mode None XF86AudioMute         spawn 'pamixer --toggle-mute'

    # Control MPRIS aware media players with playerctl (https://github.com/altdesktop/playerctl)
    riverctl map $mode None XF86AudioMedia spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPlay  spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPrev  spawn 'playerctl previous'
    riverctl map $mode None XF86AudioNext  spawn 'playerctl next'

    # Control screen backlight brightness with brightnessctl (https://github.com/Hummer12007/brightnessctl)
    riverctl map $mode None XF86MonBrightnessUp   spawn 'brightnessctl set +5%'
    riverctl map $mode None XF86MonBrightnessDown spawn 'brightnessctl set 5%-'
done

# Set background and border color
riverctl background-color 0x002b36
riverctl border-color-focused 0x93a1a1
riverctl border-color-unfocused 0x586e75

# Set keyboard repeat rate
riverctl set-repeat 50 300

# Make all views with an app-id that starts with "float" and title "foo" start floating.
riverctl rule-add -app-id 'float*' -title 'foo' float

# Make all views with app-id "bar" and any title use client-side decorations
riverctl rule-add -app-id "bar" csd

# Set the default layout generator to be rivertile and start it.
# River will send the process group of the init executable SIGTERM on exit.
riverctl default-layout rivertile
rivertile -view-padding 6 -outer-padding 6 &

# inputs
# touchpad
riverctl input pointer-2362-5-HTIX5288:00_093A:0005_Touchpad tap enabled
riverctl input pointer-2362-5-HTIX5288:00_093A:0005_Touchpad natural-scroll enabled
riverctl input pointer-2362-5-HTIX5288:00_093A:0005_Touchpad scroll-factor 0.2
